# Generated by Django 4.2.11 on 2024-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='name')),
                ('l_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'personal detail',
                'verbose_name_plural': 'personal details',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
