# Generated by Django 3.2.5 on 2024-03-13 14:40

from django.db import migrations, models
from django.utils import timezone
class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_media_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=50, verbose_name='Instagram Link')),
                ('twitter', models.CharField(max_length=50, verbose_name='twitter Link')),
                ('telegram', models.CharField(max_length=50, verbose_name='telegram Link')),
                ('linkedin', models.CharField(max_length=50, verbose_name='linkedin Link')),
                ('facebook', models.CharField(max_length=50, verbose_name='facebook Link')),
            ],
            options={
                'verbose_name': 'social_media_links',
                'verbose_name_plural': 'social_media_linkss',
            },
        ),
        migrations.AddField(
            model_name='personal_details',
            name='about_me',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='address',
            field=models.CharField(default=1, max_length=50, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='birthday',
            field=models.DateField(default=timezone.now, verbose_name='birthday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='education',
            field=models.CharField(default=1, max_length=50, verbose_name='education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='email',
            field=models.EmailField(default="ads@ads.com", max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='image_profile',
            field=models.ImageField(default="test.png", upload_to=None, verbose_name='profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='job_title',
            field=models.CharField(default=1, max_length=50, verbose_name='job title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='phone_number',
            field=models.CharField(default=1, max_length=50, verbose_name='phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='status',
            field=models.CharField(default=1, max_length=50, verbose_name='work status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='website',
            field=models.URLField(default="https://test.com", verbose_name='your website'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='f_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='l_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
    ]
