# Generated by Django 3.2.5 on 2024-03-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20240313_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='social_links',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpage.social_media_links', verbose_name='social links'),
            preserve_default=False,
        ),
    ]
