# Generated by Django 4.2.11 on 2024-03-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_personal_details_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to=None, verbose_name='Resume Files')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.personal_details')),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
