# Generated by Django 4.2.11 on 2024-03-14 08:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='skill')),
                ('percent', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.personal_details')),
            ],
            options={
                'verbose_name': 'skills',
                'verbose_name_plural': 'skillss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
