# Generated by Django 4.2.11 on 2024-03-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_details',
            name='social_links',
        ),
        migrations.AddField(
            model_name='social_media_links',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpage.personal_details', verbose_name='social links'),
            preserve_default=False,
        ),
    ]
