# Generated by Django 4.2.11 on 2024-03-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_remove_personal_details_social_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='set_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainpage.personal_details', verbose_name='user')),
            ],
        ),
    ]
